import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { Montserrat } from "next/font/google";
import MainLayout from "@/components/layout/main-layout";

const montserrat = Montserrat({
  subsets: ["latin"], // Yoki ["latin", "cyrillic", "vietnamese"]
  weight: ["400", "500", "600"], // Faqat kerakli vaznlarni yuklaymiz
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <MainLayout>{children}</MainLayout>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
